{{- if .Values.web.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "zally.web.fullname" . }}
  labels:
{{ include "zally.web.labels" . | indent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "zally.web.matchLabels" . | nindent 6 }}
  replicas: {{ .Values.web.replicaCount }}
  template:
    metadata:
      labels:
        {{- include "zally.web.labels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      securityContext:
        {{- toYaml .Values.web.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ template "zally.name" . }}-{{ .Values.web.name }}
          securityContext:
            {{- toYaml .Values.web.securityContext | nindent 12 }}
          image: "{{ .Values.web.image.repository }}:{{ .Values.web.image.tag }}"
          imagePullPolicy: {{ .Values.web.image.pullPolicy }}
          args:
          {{- range $key, $value := .Values.web.extraArgs }}
          {{- if $value }}
            - --{{ $key }}={{ $value }}
          {{- else }}
            - --{{ $key }}
          {{- end }}
          {{- end }}
          ports:
            - name: http
              containerPort: 3000
          {{- if .Values.web.readinessProbe.enabled }}
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 0
            periodSeconds: 5
            failureThreshold: 2
          {{- end }}
          {{- if .Values.web.livenessProbe.enabled }}
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 0
            periodSeconds: 5
            failureThreshold: 10
          {{- end }}
          resources:
            {{- toYaml .Values.web.resources | nindent 12 }}
          env:
            {{- range $key, $value := .Values.web.extraEnv }}
            - name: {{ $key }}
              value: {{ $value }}
            {{- end }}
            - name: ZALLY_API_URL
              value: '{{ .Values.web.apiUrl }}'
      {{- with .Values.web.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.web.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.web.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.imagePullSecrets | indent 8 }}
    {{- end }}
{{- end }}