name: Continuous Deployment - Helm

on:
  push:
    branches: [ main ]

jobs:
  release:
    name: Helm Chart Release
    runs-on: ubuntu-latest

    steps:
      - name: Setup Environment
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Package
        shell: bash
        run: release-chart.sh
        env:
          TERM: xterm-256color

      - name: Create Pull Request branch
        run: |
          git checkout -b gh-pages-pull-request

      # Note that will fail if branch already exists.
      - name: Push Git Branch
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages-pull-request

      # Note that will silently fail if PR already exists.
      - name: Create Pull Request
        uses: repo-sync/pull-request@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          source_branch: gh-pages-pull-request
          destination_branch: gh-pages
          pr_title: "Helm Chart: Update Helm repository"
          pr_body: "Automatically created from Helm CD workflow."